{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7cefb520",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting torchmetrics\n",
      "  Downloading torchmetrics-1.8.2-py3-none-any.whl.metadata (22 kB)\n",
      "Collecting pyqubo\n",
      "  Downloading pyqubo-1.5.0-cp312-cp312-win_amd64.whl.metadata (7.2 kB)\n",
      "Collecting dwave-neal\n",
      "  Downloading dwave_neal-0.6.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "Requirement already satisfied: numpy>1.20.0 in d:\\new folder\\lib\\site-packages (from torchmetrics) (2.3.3)\n",
      "Requirement already satisfied: packaging>17.1 in d:\\new folder\\lib\\site-packages (from torchmetrics) (24.1)\n",
      "Requirement already satisfied: torch>=2.0.0 in d:\\new folder\\lib\\site-packages (from torchmetrics) (2.8.0)\n",
      "Collecting lightning-utilities>=0.8.0 (from torchmetrics)\n",
      "  Downloading lightning_utilities-0.15.2-py3-none-any.whl.metadata (5.7 kB)\n",
      "Collecting dimod<0.13,>=0.9.14 (from pyqubo)\n",
      "  Downloading dimod-0.12.21-cp312-cp312-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting Deprecated>=1.2.12 (from pyqubo)\n",
      "  Downloading Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)\n",
      "Requirement already satisfied: six>=1.15.0 in d:\\new folder\\lib\\site-packages (from pyqubo) (1.16.0)\n",
      "Collecting dwave-samplers<2.0.0,>=1.0.0 (from dwave-neal)\n",
      "  Downloading dwave_samplers-1.6.0-cp312-cp312-win_amd64.whl.metadata (12 kB)\n",
      "Requirement already satisfied: networkx>=3.0 in d:\\new folder\\lib\\site-packages (from dwave-samplers<2.0.0,>=1.0.0->dwave-neal) (3.3)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in d:\\new folder\\lib\\site-packages (from Deprecated>=1.2.12->pyqubo) (1.14.1)\n",
      "Requirement already satisfied: setuptools in d:\\new folder\\lib\\site-packages (from lightning-utilities>=0.8.0->torchmetrics) (75.1.0)\n",
      "Requirement already satisfied: typing_extensions in d:\\new folder\\lib\\site-packages (from lightning-utilities>=0.8.0->torchmetrics) (4.11.0)\n",
      "Requirement already satisfied: filelock in d:\\new folder\\lib\\site-packages (from torch>=2.0.0->torchmetrics) (3.13.1)\n",
      "Requirement already satisfied: sympy>=1.13.3 in d:\\new folder\\lib\\site-packages (from torch>=2.0.0->torchmetrics) (1.14.0)\n",
      "Requirement already satisfied: jinja2 in d:\\new folder\\lib\\site-packages (from torch>=2.0.0->torchmetrics) (3.1.4)\n",
      "Requirement already satisfied: fsspec in d:\\new folder\\lib\\site-packages (from torch>=2.0.0->torchmetrics) (2024.6.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\\new folder\\lib\\site-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in d:\\new folder\\lib\\site-packages (from jinja2->torch>=2.0.0->torchmetrics) (2.1.3)\n",
      "Downloading torchmetrics-1.8.2-py3-none-any.whl (983 kB)\n",
      "   ---------------------------------------- 0.0/983.2 kB ? eta -:--:--\n",
      "   ---------------------------------------- 983.2/983.2 kB 7.7 MB/s  0:00:00\n",
      "Downloading pyqubo-1.5.0-cp312-cp312-win_amd64.whl (403 kB)\n",
      "Downloading dimod-0.12.21-cp312-cp312-win_amd64.whl (5.2 MB)\n",
      "   ---------------------------------------- 0.0/5.2 MB ? eta -:--:--\n",
      "   -------- ------------------------------- 1.0/5.2 MB 8.4 MB/s eta 0:00:01\n",
      "   ---------------- ----------------------- 2.1/5.2 MB 5.9 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 3.1/5.2 MB 5.3 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 4.2/5.2 MB 5.0 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 5.0/5.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 5.2/5.2 MB 4.7 MB/s  0:00:01\n",
      "Downloading dwave_neal-0.6.0-py3-none-any.whl (8.7 kB)\n",
      "Downloading dwave_samplers-1.6.0-cp312-cp312-win_amd64.whl (2.6 MB)\n",
      "   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--\n",
      "   ---------------- ----------------------- 1.0/2.6 MB 12.7 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 2.4/2.6 MB 5.8 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.6/2.6 MB 5.9 MB/s  0:00:00\n",
      "Downloading Deprecated-1.2.18-py2.py3-none-any.whl (10.0 kB)\n",
      "Downloading lightning_utilities-0.15.2-py3-none-any.whl (29 kB)\n",
      "Installing collected packages: lightning-utilities, dimod, Deprecated, dwave-samplers, torchmetrics, dwave-neal, pyqubo\n",
      "\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ---------------------------------------- 0/7 [lightning-utilities]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----- ---------------------------------- 1/7 [dimod]\n",
      "   ----------- ---------------------------- 2/7 [Deprecated]\n",
      "   ----------------- ---------------------- 3/7 [dwave-samplers]\n",
      "   ----------------- ---------------------- 3/7 [dwave-samplers]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------- ----------------- 4/7 [torchmetrics]\n",
      "   ---------------------------- ----------- 5/7 [dwave-neal]\n",
      "   ---------------------------------- ----- 6/7 [pyqubo]\n",
      "   ---------------------------------- ----- 6/7 [pyqubo]\n",
      "   ---------------------------------------- 7/7 [pyqubo]\n",
      "\n",
      "Successfully installed Deprecated-1.2.18 dimod-0.12.21 dwave-neal-0.6.0 dwave-samplers-1.6.0 lightning-utilities-0.15.2 pyqubo-1.5.0 torchmetrics-1.8.2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution ~cipy (d:\\New folder\\Lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution ~cipy (d:\\New folder\\Lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution ~cipy (d:\\New folder\\Lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "!pip install torchmetrics pyqubo dwave-neal"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
